//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetroApi.Entities
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class StartToEnd
    {
        public int Id { get; set; }
        public Nullable<int> StationStartId { get; set; }
        public Nullable<int> StationEndId { get; set; }
        public Nullable<int> BranchId { get; set; }

        [JsonIgnore]

        public virtual Branch Branch { get; set; }

        [JsonIgnore]
        public virtual Station Station { get; set; }

        [JsonIgnore]
        public virtual Station Station1 { get; set; }
    }
}
